// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Casts a ray from a screen-space point (in pixels, matching the active
/// renderer's own width/height) and returns the world-space point where
/// it hits the currently loaded mesh, if any.
(double, double, double)? pick({required double x, required double y}) =>
    RustLib.instance.api.crateApiSimplePick(x: x, y: y);

/// Casts a ray from a screen-space point and, if it hits the mesh, places
/// a new bone there in the current skeleton. If `parent` is given, the
/// new bone becomes that bone's child (its position is stored relative
/// to the parent, per the skeleton's bind-pose convention); otherwise
/// it's a new root bone. Returns the new bone's index and world-space
/// position, or `None` if the click missed the mesh.
(BigInt, double, double, double)? placeBone({
  required double x,
  required double y,
  BigInt? parent,
}) => RustLib.instance.api.crateApiSimplePlaceBone(x: x, y: y, parent: parent);

/// Returns the number of bones placed so far in the current skeleton.
BigInt boneCount() => RustLib.instance.api.crateApiSimpleBoneCount();

/// Runs auto skin-weighting (Section 3c's naive distance-based scheme)
/// against the current skeleton and the active mesh, storing the result
/// for inspection/editing. Returns false if there's no active renderer or
/// no bones placed yet.
bool computeWeights() => RustLib.instance.api.crateApiSimpleComputeWeights();

/// Returns the given vertex's currently dominant bone and its weight, if
/// weights have been computed yet.
(BigInt, double)? getVertexDominantBone({required BigInt vertexIndex}) =>
    RustLib.instance.api.crateApiSimpleGetVertexDominantBone(
      vertexIndex: vertexIndex,
    );

/// Rotates one bone to an absolute angle (degrees, around Z) measured
/// from its original bind pose — not from wherever it currently is — so
/// repeated calls don't compound. Recomputes skinning matrices for the
/// whole skeleton and uploads them to the GPU. Returns false if the bone
/// index is out of range or there's no active renderer.
bool rotateBone({required BigInt boneIndex, required double angleDegrees}) =>
    RustLib.instance.api.crateApiSimpleRotateBone(
      boneIndex: boneIndex,
      angleDegrees: angleDegrees,
    );

/// Drags a joint: rotates the joint's PARENT in 3D, around the parent's
/// own position, so the dragged joint swings onto the cursor at screen
/// pixel (x, y). The cursor is projected onto a plane through the joint
/// that faces the camera, so the joint can move in any direction the
/// camera sees (orbit the camera to bend front/back). Returns false for
/// root joints, bad indices, or when there's no active renderer.
bool dragBone({
  required BigInt boneIndex,
  required double x,
  required double y,
}) => RustLib.instance.api.crateApiSimpleDragBone(
  boneIndex: boneIndex,
  x: x,
  y: y,
);

/// IK drag: moves the joint onto the cursor at screen pixel (x, y) by
/// bending the two joints above it (drag an ankle and the hip and knee
/// follow). The cursor is projected onto a plane through the joint that
/// faces the camera. Returns false if the joint lacks a parent and
/// grandparent, or there's no active renderer.
bool dragLimb({
  required BigInt boneIndex,
  required double x,
  required double y,
}) => RustLib.instance.api.crateApiSimpleDragLimb(
  boneIndex: boneIndex,
  x: x,
  y: y,
);

/// Puts every joint back to its rest pose, keeping the skeleton and
/// skin weights as they are.
void resetPose() => RustLib.instance.api.crateApiSimpleResetPose();

/// Undo for bone placement: removes the most recently placed bone and
/// returns (true, its parent) so the caller can select that parent, or
/// (false, None) if there is nothing to remove. Skin weights computed
/// earlier still refer to the old bone list, so recompute them afterward.
(bool, BigInt?) undoLastBone() =>
    RustLib.instance.api.crateApiSimpleUndoLastBone();

/// Records the current pose as a keyframe at `time` (seconds). A key
/// already at that time is replaced. Returns how many keys there are now.
BigInt addKeyframe({required double time}) =>
    RustLib.instance.api.crateApiSimpleAddKeyframe(time: time);

/// The time (seconds) of every keyframe, earliest first.
Float32List keyframeTimes() =>
    RustLib.instance.api.crateApiSimpleKeyframeTimes();

/// Deletes the keyframe nearest `time` if one is within 0.05 s of it.
/// Returns whether a key was removed.
bool deleteKeyframeAt({required double time}) =>
    RustLib.instance.api.crateApiSimpleDeleteKeyframeAt(time: time);

/// Poses the character as the keyframes say it looks at `time` (seconds).
/// Returns false, leaving the pose alone, if there are no keyframes.
bool seekToTime({required double time}) =>
    RustLib.instance.api.crateApiSimpleSeekToTime(time: time);

/// Makes the keys repeat: a cycle runs from the first key until
/// `end_time` (seconds), then starts over, over and over. `end_time` has
/// to be past the last key. Returns whether the repeat was set.
bool setRepeatEnd({required double endTime}) =>
    RustLib.instance.api.crateApiSimpleSetRepeatEnd(endTime: endTime);

/// Stops the keys from repeating.
void clearRepeat() => RustLib.instance.api.crateApiSimpleClearRepeat();

/// How long one repeat of the keys lasts (seconds), or None if they don't repeat.
double? repeatPeriod() => RustLib.instance.api.crateApiSimpleRepeatPeriod();

/// Moves the whole character so its root joint follows the cursor at
/// screen pixel (x, y), on a plane through the root that faces the camera.
/// Returns false if there is no skeleton or no active renderer.
bool moveCharacter({required double x, required double y}) =>
    RustLib.instance.api.crateApiSimpleMoveCharacter(x: x, y: y);

/// Zooms the camera: a factor above 1 moves it away, below 1 closer.
void zoomCamera({required double factor}) =>
    RustLib.instance.api.crateApiSimpleZoomCamera(factor: factor);

/// Makes the character travel at `speed` units per second along the
/// camera's right-hand direction as it looks right now (negative goes
/// left), starting at the first key. Combines with keyed movement and
/// repeats. Returns false if there is no active renderer.
bool setTravelSpeed({required double speed}) =>
    RustLib.instance.api.crateApiSimpleSetTravelSpeed(speed: speed);

/// The Travel slider's current value (units per second).
double travelSpeed() => RustLib.instance.api.crateApiSimpleTravelSpeed();

/// Saves the skeleton, skin weights and animation to `path` as a JSON
/// file. Returns (true, summary) on success or (false, reason) on failure.
(bool, String) saveProject({required String path}) =>
    RustLib.instance.api.crateApiSimpleSaveProject(path: path);

/// Loads a project saved with `save_project` onto the model that is
/// currently open, replacing the skeleton, skin weights and animation.
/// The project must have been saved for a model with the same number of
/// vertices. Returns (true, summary) or (false, reason).
(bool, String) loadProject({required String path}) =>
    RustLib.instance.api.crateApiSimpleLoadProject(path: path);

/// Screen-space (pixel) position of every joint in its current posed
/// state, indexed the same as the skeleton's bones. An entry is None if
/// that joint is behind the camera.
List<(double, double)?> jointScreenPositions() =>
    RustLib.instance.api.crateApiSimpleJointScreenPositions();

List<BigInt?> boneParents() => RustLib.instance.api.crateApiSimpleBoneParents();

/// Clears the current skeleton and any computed weights, so you can
/// start placing bones over from a clean state.
void resetSkeleton() => RustLib.instance.api.crateApiSimpleResetSkeleton();

/// Orbits the camera by the given angle deltas (radians) around its
/// current target. Positive delta_yaw orbits rightward, positive
/// delta_pitch orbits upward.
void orbitCamera({required double deltaYaw, required double deltaPitch}) =>
    RustLib.instance.api.crateApiSimpleOrbitCamera(
      deltaYaw: deltaYaw,
      deltaPitch: deltaPitch,
    );

bool setVertexWeight({
  required BigInt vertexIndex,
  required BigInt boneIndex,
}) => RustLib.instance.api.crateApiSimpleSetVertexWeight(
  vertexIndex: vertexIndex,
  boneIndex: boneIndex,
);
